# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df23994a7bb370d0d3a98c68652e9cd9a341a7c9675821a717aae241cdfed4b6b2c4f27971a34b2753f0f0c59f5a79499281e8216352c07edaf8a4e6eb454216

test:
  secret_key_base: f732c2ed4318c12b4f31d63a5a27407538de00158ea6633b1dd3f2d3f432e38a0336eb32f62dae4b8d05d807324bf777a98ebda17cbd805a9cfdc896e9e45fdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
